// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bulletinStructure.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message_Commands int32

const (
	Message_HELP      Message_Commands = 0
	Message_REGISTER  Message_Commands = 1
	Message_GET       Message_Commands = 2
	Message_FLUSH_ALL Message_Commands = 3
)

var Message_Commands_name = map[int32]string{
	0: "HELP",
	1: "REGISTER",
	2: "GET",
	3: "FLUSH_ALL",
}

var Message_Commands_value = map[string]int32{
	"HELP":      0,
	"REGISTER":  1,
	"GET":       2,
	"FLUSH_ALL": 3,
}

func (x Message_Commands) String() string {
	return proto.EnumName(Message_Commands_name, int32(x))
}

func (Message_Commands) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9a985add4a676159, []int{0, 0}
}

type Message struct {
	Cmd                  Message_Commands `protobuf:"varint,1,opt,name=cmd,proto3,enum=main.Message_Commands" json:"cmd,omitempty"`
	Args                 string           `protobuf:"bytes,2,opt,name=args,proto3" json:"args,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_9a985add4a676159, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetCmd() Message_Commands {
	if m != nil {
		return m.Cmd
	}
	return Message_HELP
}

func (m *Message) GetArgs() string {
	if m != nil {
		return m.Args
	}
	return ""
}

type Topic struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Url                  string   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Err                  string   `protobuf:"bytes,3,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Topic) Reset()         { *m = Topic{} }
func (m *Topic) String() string { return proto.CompactTextString(m) }
func (*Topic) ProtoMessage()    {}
func (*Topic) Descriptor() ([]byte, []int) {
	return fileDescriptor_9a985add4a676159, []int{1}
}

func (m *Topic) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Topic.Unmarshal(m, b)
}
func (m *Topic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Topic.Marshal(b, m, deterministic)
}
func (m *Topic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Topic.Merge(m, src)
}
func (m *Topic) XXX_Size() int {
	return xxx_messageInfo_Topic.Size(m)
}
func (m *Topic) XXX_DiscardUnknown() {
	xxx_messageInfo_Topic.DiscardUnknown(m)
}

var xxx_messageInfo_Topic proto.InternalMessageInfo

func (m *Topic) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Topic) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Topic) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func init() {
	proto.RegisterEnum("main.Message_Commands", Message_Commands_name, Message_Commands_value)
	proto.RegisterType((*Message)(nil), "main.Message")
	proto.RegisterType((*Topic)(nil), "main.Topic")
}

func init() { proto.RegisterFile("bulletinStructure.proto", fileDescriptor_9a985add4a676159) }

var fileDescriptor_9a985add4a676159 = []byte{
	// 217 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0x8f, 0x4d, 0x4b, 0xc4, 0x30,
	0x10, 0x86, 0xcd, 0xa6, 0xba, 0xed, 0xa0, 0x12, 0xe6, 0xa0, 0x3d, 0x2e, 0x3d, 0xf5, 0xd4, 0x83,
	0xde, 0xbc, 0x88, 0x48, 0xdd, 0x15, 0x2a, 0x48, 0x5a, 0xcf, 0x92, 0xed, 0x86, 0xa5, 0xd0, 0x34,
	0xcb, 0x24, 0xf9, 0x05, 0xfe, 0x71, 0x49, 0x5c, 0x6f, 0x0f, 0xef, 0xfb, 0x30, 0x1f, 0x70, 0xbf,
	0x0f, 0xf3, 0xac, 0xfd, 0xb4, 0xf4, 0x9e, 0xc2, 0xe8, 0x03, 0xe9, 0xe6, 0x44, 0xd6, 0x5b, 0xcc,
	0x8c, 0x9a, 0x96, 0xea, 0x87, 0xc1, 0xfa, 0x43, 0x3b, 0xa7, 0x8e, 0x1a, 0x6b, 0xe0, 0xa3, 0x39,
	0x94, 0x6c, 0xc3, 0xea, 0xdb, 0x87, 0xbb, 0x26, 0xf6, 0xcd, 0xb9, 0x6b, 0x5e, 0xad, 0x31, 0x6a,
	0x39, 0x38, 0x19, 0x15, 0x44, 0xc8, 0x14, 0x1d, 0x5d, 0xb9, 0xda, 0xb0, 0xba, 0x90, 0x89, 0xab,
	0x27, 0xc8, 0xff, 0x25, 0xcc, 0x21, 0xdb, 0xb5, 0xdd, 0xa7, 0xb8, 0xc0, 0x6b, 0xc8, 0x65, 0xbb,
	0x7d, 0xef, 0x87, 0x56, 0x0a, 0x86, 0x6b, 0xe0, 0xdb, 0x76, 0x10, 0x2b, 0xbc, 0x81, 0xe2, 0xad,
	0xfb, 0xea, 0x77, 0xdf, 0x2f, 0x5d, 0x27, 0x78, 0xf5, 0x0c, 0x97, 0x83, 0x3d, 0x4d, 0x63, 0x1c,
	0xbc, 0x28, 0xa3, 0xd3, 0x0d, 0x85, 0x4c, 0x8c, 0x02, 0x78, 0xa0, 0xf9, 0xbc, 0x2b, 0x62, 0x4c,
	0x34, 0x51, 0xc9, 0xff, 0x12, 0x4d, 0xb4, 0xbf, 0x4a, 0x3f, 0x3d, 0xfe, 0x06, 0x00, 0x00, 0xff,
	0xff, 0x40, 0x2b, 0x3d, 0xc4, 0xee, 0x00, 0x00, 0x00,
}
