// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bulletinStructure.proto

package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Message_Commands int32

const (
	Message_HELP     Message_Commands = 0
	Message_REGISTER Message_Commands = 1
	Message_GET      Message_Commands = 2
)

var Message_Commands_name = map[int32]string{
	0: "HELP",
	1: "REGISTER",
	2: "GET",
}
var Message_Commands_value = map[string]int32{
	"HELP":     0,
	"REGISTER": 1,
	"GET":      2,
}

func (x Message_Commands) String() string {
	return proto.EnumName(Message_Commands_name, int32(x))
}
func (Message_Commands) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bulletinStructure_0f8a7124e3949605, []int{0, 0}
}

type Message struct {
	Cmd                  Message_Commands `protobuf:"varint,1,opt,name=cmd,proto3,enum=main.Message_Commands" json:"cmd,omitempty"`
	Args                 string           `protobuf:"bytes,2,opt,name=args,proto3" json:"args,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_bulletinStructure_0f8a7124e3949605, []int{0}
}
func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (dst *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(dst, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetCmd() Message_Commands {
	if m != nil {
		return m.Cmd
	}
	return Message_HELP
}

func (m *Message) GetArgs() string {
	if m != nil {
		return m.Args
	}
	return ""
}

type Topic struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Url                  string   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Topic) Reset()         { *m = Topic{} }
func (m *Topic) String() string { return proto.CompactTextString(m) }
func (*Topic) ProtoMessage()    {}
func (*Topic) Descriptor() ([]byte, []int) {
	return fileDescriptor_bulletinStructure_0f8a7124e3949605, []int{1}
}
func (m *Topic) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Topic.Unmarshal(m, b)
}
func (m *Topic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Topic.Marshal(b, m, deterministic)
}
func (dst *Topic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Topic.Merge(dst, src)
}
func (m *Topic) XXX_Size() int {
	return xxx_messageInfo_Topic.Size(m)
}
func (m *Topic) XXX_DiscardUnknown() {
	xxx_messageInfo_Topic.DiscardUnknown(m)
}

var xxx_messageInfo_Topic proto.InternalMessageInfo

func (m *Topic) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Topic) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func init() {
	proto.RegisterType((*Message)(nil), "main.Message")
	proto.RegisterType((*Topic)(nil), "main.Topic")
	proto.RegisterEnum("main.Message_Commands", Message_Commands_name, Message_Commands_value)
}

func init() {
	proto.RegisterFile("bulletinStructure.proto", fileDescriptor_bulletinStructure_0f8a7124e3949605)
}

var fileDescriptor_bulletinStructure_0f8a7124e3949605 = []byte{
	// 190 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0x8e, 0xcd, 0x4a, 0xc4, 0x30,
	0x14, 0x46, 0xcd, 0xb4, 0x3a, 0x9d, 0x8b, 0x48, 0xb8, 0x0b, 0x9d, 0x65, 0xe9, 0xaa, 0x20, 0x66,
	0xa1, 0x8f, 0x20, 0xa1, 0x0a, 0x0a, 0x92, 0xf6, 0x05, 0xd2, 0x36, 0x94, 0x42, 0x93, 0x94, 0xfc,
	0xbc, 0xbf, 0x24, 0x74, 0x76, 0x07, 0xbe, 0xc3, 0xb9, 0x17, 0x5e, 0xc6, 0xb8, 0x6d, 0x2a, 0xac,
	0xa6, 0x0f, 0x2e, 0x4e, 0x21, 0x3a, 0xc5, 0x76, 0x67, 0x83, 0xc5, 0x52, 0xcb, 0xd5, 0x34, 0x01,
	0xce, 0xbf, 0xca, 0x7b, 0xb9, 0x28, 0x6c, 0xa1, 0x98, 0xf4, 0x7c, 0x25, 0x35, 0x69, 0x9f, 0xde,
	0x9f, 0x59, 0x9a, 0xd9, 0xb1, 0xb1, 0x4f, 0xab, 0xb5, 0x34, 0xb3, 0x17, 0x49, 0x41, 0x84, 0x52,
	0xba, 0xc5, 0x5f, 0x4f, 0x35, 0x69, 0x2f, 0x22, 0x73, 0xf3, 0x0a, 0xd5, 0x4d, 0xc2, 0x0a, 0xca,
	0x2f, 0xfe, 0xf3, 0x47, 0xef, 0xf0, 0x11, 0x2a, 0xc1, 0xbb, 0xef, 0x7e, 0xe0, 0x82, 0x12, 0x3c,
	0x43, 0xd1, 0xf1, 0x81, 0x9e, 0x9a, 0x37, 0xb8, 0x1f, 0xec, 0xbe, 0x4e, 0xa9, 0x64, 0xa4, 0x56,
	0xf9, 0xe8, 0x45, 0x64, 0x46, 0x0a, 0x45, 0x74, 0xdb, 0x11, 0x4f, 0x38, 0x3e, 0xe4, 0x8f, 0x3f,
	0xfe, 0x03, 0x00, 0x00, 0xff, 0xff, 0xe9, 0xe9, 0x79, 0x63, 0xcc, 0x00, 0x00, 0x00,
}
