// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messageStructure.proto

package protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Message_Commands int32

const (
	Message_HELP     Message_Commands = 0
	Message_REGISTER Message_Commands = 1
	Message_GET      Message_Commands = 2
)

var Message_Commands_name = map[int32]string{
	0: "HELP",
	1: "REGISTER",
	2: "GET",
}
var Message_Commands_value = map[string]int32{
	"HELP":     0,
	"REGISTER": 1,
	"GET":      2,
}

func (x Message_Commands) String() string {
	return proto.EnumName(Message_Commands_name, int32(x))
}
func (Message_Commands) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_messageStructure_1e84fc6ac1b5fd43, []int{0, 0}
}

type Message struct {
	Cmd                  Message_Commands `protobuf:"varint,1,opt,name=cmd,proto3,enum=main.Message_Commands" json:"cmd,omitempty"`
	Args                 string           `protobuf:"bytes,2,opt,name=args,proto3" json:"args,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_messageStructure_1e84fc6ac1b5fd43, []int{0}
}
func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (dst *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(dst, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetCmd() Message_Commands {
	if m != nil {
		return m.Cmd
	}
	return Message_HELP
}

func (m *Message) GetArgs() string {
	if m != nil {
		return m.Args
	}
	return ""
}

func init() {
	proto.RegisterType((*Message)(nil), "main.Message")
	proto.RegisterEnum("main.Message_Commands", Message_Commands_name, Message_Commands_value)
}

func init() {
	proto.RegisterFile("messageStructure.proto", fileDescriptor_messageStructure_1e84fc6ac1b5fd43)
}

var fileDescriptor_messageStructure_1e84fc6ac1b5fd43 = []byte{
	// 155 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xcb, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0x0d, 0x2e, 0x29, 0x2a, 0x4d, 0x2e, 0x29, 0x2d, 0x4a, 0xd5, 0x2b, 0x28, 0xca,
	0x2f, 0xc9, 0x17, 0x62, 0xc9, 0x4d, 0xcc, 0xcc, 0x53, 0x2a, 0xe1, 0x62, 0xf7, 0x85, 0xc8, 0x0b,
	0x69, 0x70, 0x31, 0x27, 0xe7, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0xf0, 0x19, 0x89, 0xe9, 0x81,
	0xa4, 0xf5, 0xa0, 0x72, 0x7a, 0xce, 0xf9, 0xb9, 0xb9, 0x89, 0x79, 0x29, 0xc5, 0x41, 0x20, 0x25,
	0x42, 0x42, 0x5c, 0x2c, 0x89, 0x45, 0xe9, 0xc5, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x60,
	0xb6, 0x92, 0x36, 0x17, 0x07, 0x4c, 0x91, 0x10, 0x07, 0x17, 0x8b, 0x87, 0xab, 0x4f, 0x80, 0x00,
	0x83, 0x10, 0x0f, 0x17, 0x47, 0x90, 0xab, 0xbb, 0x67, 0x70, 0x88, 0x6b, 0x90, 0x00, 0xa3, 0x10,
	0x3b, 0x17, 0xb3, 0xbb, 0x6b, 0x88, 0x00, 0x53, 0x12, 0x1b, 0xd8, 0x09, 0xc6, 0x80, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x1b, 0xee, 0x61, 0xa1, 0x9c, 0x00, 0x00, 0x00,
}
